### PR TITLE
show frontend changes as png in backend

### PR DESCRIPTION
**Pull request by joshcwinton**
Show a png when a change is made in environment

Issue: Closes #

### Frontend:
- 
### Backend:
- call `renderenvironment` whenever changes are made to environment
- add support for 3D keywords in `renderenvironment`

### CODE REVIEW

**Review by JasperCheung — APPROVED** [review]
approved, but does it make more sense to call renderEnviroment at the end of like `doAction`?

**Comment by joshcwinton** [comment]
> approved, but does it make more sense to call renderEnviroment at the end of like `doAction`?

actually yeah lemme change it @JasperCheung

**Comment by joshcwinton** [comment]
sorry nvm the merge is gonna be easier if I do it on another branch

**Comment by joshcwinton** [comment]
@JasperCheung had another look at this and since `doAction` has a bunch of different returns, I'm not sure it's easier

lmk whatcha think

**Comment by JasperCheung** [comment]
> @JasperCheung had another look at this and since `doAction` has a bunch of different returns, I'm not sure it's easier
> 
> lmk whatcha think

@joshcwinton yeah thats what i thought, so im fine with leaving it.

**Comment by joshcwinton** [comment]
@JasperCheung ai bet lgtm

**Pull request merged**
